title: Phi Quang Đạt
description:  Chào mừng mọi người
url: https://phiquangdat.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
